### ISSUE TITLE
 image is not a valid size specification

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/c3-wolfram-face-swap#6]
URL: /en/projects/c3-wolfram-face-swap/complete Does not work: image is not a valid size specification?

**Comment by PhilipHarney** [comment]
Looked through all the code, can't find an issue, but need to setup my Pi and load up mathematica to be sure. Will block off some time to do that next week. It's also possible that there's a bracket missing in their implementation, as the commands get seriously nested by the end.

**Comment by PhilipHarney** [comment]
Fixed
